### PR TITLE
Bug 1210314 settings : Initial  Visual Implementation & Some Settings Fixes

### PR DESCRIPTION
**Pull request by Vinay18Mishra**
Initial Visual Design Changes:
    1.  apps/settings/elements/about.html
    ⁃ Change <p> to <Span>, is same as VD. 
    2.  apps/settings/style/lists.css
    3.  apps/settings/style/screen_lock.css
    4.  apps/settings/style/settings.css
    5.  apps/system/style/edges/edges.css
    6.  shared/style/buttons.css
    7.  shared/style/headers.css
    8.  shared/style/value_selector.css
    ⁃ Change in Font Size, style, width and etc 
    9.  shared/style/switches.css
    ⁃ change the on/ off to capital letter, font and style.
    10. shared/elements/gaia-header/dist/gaia-header.js 
    11. shared/elements/gaia-header/gaia-header.js 
    12. shared/elements/gaia-theme/gaia-theme.css 
    ⁃ Change in gaia-header as  per VD, changes are like background color, back arrow style, Gaia-Header height and etc, 

Bug 1210314- App Settings implementation Fixes:
    ⁃ apps/communications/contacts/js/export/bt.js
    ⁃ We have removed this function and initialise this value, wherever we needed as per UX.

@Ashish-Developer @pgmanutd

### CODE REVIEW

**Comment by egorlevichev** [comment]
Pull request shall not contain any commit not related to implemented changes, to achive this the branch with changes to be PRed shall be rebased on top of target branch right before submitting PR.

**Comment by Vinay18Mishra** [comment]
@egorlevichev, i haven't understood your comments. can you elaborate please...

**Comment by egorlevichev** [comment]
@Vinay18Mishra sure, first 5 commits in this PR looks like result of some merge onto your development branch. Instead of merging, you shall 'rebase' your changes on top of target branch before making PR.

**Comment by Vinay18Mishra** [comment]
there are some unnecessary commits. Please ignore this pull request.

**Pull request closed without merging**
