### PR TITLE
Bug 1210314 - Settings: Fixed issues given by reviewer

### PR DESCRIPTION
**Pull request by insjinger**
Please Review it @Ashish-Developer

### CODE REVIEW

**Comment by TatianaMigacheva** [comment]
ok to test

**Comment by TatianaMigacheva** [comment]
ok to test

**Comment by TatianaMigacheva** [comment]
ok to test

**Comment by TatianaMigacheva** [comment]
Harman-Jenkins: pr_review_passed

TatianaMigacheva: Verified that below Lint errors exist in Mozilla plaform. So we will skip them.

Lint errors:
:( -2 errors has been added to apps/settings/style/settings.css.
:( -1 warnings has been added to apps/settings/style/settings.css.
Errors in /export/jenkins/jobs/Gaia_PR_checker/workspace/checkstyle/gaia/apps/settings/style/settings.css
Duplicate property 'border' found. line 1399, col 3
Duplicate property 'border' found. line 1412, col 3
Warnings in /export/jenkins/jobs/Gaia_PR_checker/workspace/checkstyle/gaia/apps/settings/style/settings.css
Use of !important line 148, col 3
Use of !important line 205, col 3
Use of !important line 209, col 3
Use of !important line 319, col 3
Use of !important line 699, col 3
Use of !important line 703, col 3
Use of !important line 876, col 3
Use of !important line 979, col 3
Too many floats (10), you're probably using them for layout. Consider using a grid system instead. line undefined, col undefined
Too many font-size declarations (29), abstraction needed. line undefined, col undefined

shared/style/confirm.css has new errors/warnings.
Warnings in /export/jenkins/jobs/Gaia_PR_checker/workspace/checkstyle/gaia/shared/style/confirm.css
Values of 0 shouldn't have units specified. line 313, col 12
Too many font-size declarations (16), abstraction needed. line undefined, col undefined

**Comment by TatianaMigacheva** [comment]
Harman-Jenkins: pr_review_passed

TatianaMigacheva: Verified that below Lint errors exist in Mozilla plaform. So we will skip them.

Lint errors:
:( -1 errors has been added to apps/settings/style/settings.css.
:( -1 warnings has been added to apps/settings/style/settings.css.
Errors in /export/jenkins/jobs/Gaia_PR_checker/workspace/checkstyle/gaia/apps/settings/style/settings.css
Duplicate property 'border' found. line 1412, col 3
Warnings in /export/jenkins/jobs/Gaia_PR_checker/workspace/checkstyle/gaia/apps/settings/style/settings.css
Use of !important line 148, col 3
Use of !important line 205, col 3
Use of !important line 209, col 3
Use of !important line 319, col 3
Use of !important line 699, col 3
Use of !important line 703, col 3
Use of !important line 876, col 3
Use of !important line 979, col 3
Too many floats (10), you're probably using them for layout. Consider using a grid system instead. line undefined, col undefined
Too many font-size declarations (29), abstraction needed. line undefined, col undefined

shared/style/confirm.css has new errors/warnings.
Warnings in /export/jenkins/jobs/Gaia_PR_checker/workspace/checkstyle/gaia/shared/style/confirm.css
Values of 0 shouldn't have units specified. line 313, col 12
Too many font-size declarations (16), abstraction needed. line undefined, col undefined

**Comment by TatianaMigacheva** [comment]
Harman-Jenkins: pr_review_passed

TatianaMigacheva: Verified that below Lint errors exist in Mozilla plaform. So we will skip them. 

Lint errors:
:( -1 warnings has been added to apps/settings/style/settings.css.
Warnings in /export/jenkins/jobs/Gaia_PR_checker/workspace/checkstyle/gaia/apps/settings/style/settings.css
Use of !important line 148, col 3
Use of !important line 205, col 3
Use of !important line 209, col 3
Use of !important line 319, col 3
Use of !important line 699, col 3
Use of !important line 703, col 3
Use of !important line 876, col 3
Use of !important line 979, col 3
Too many floats (10), you're probably using them for layout. Consider using a grid system instead. line undefined, col undefined
Too many font-size declarations (29), abstraction needed. line undefined, col undefined

shared/style/confirm.css has new errors/warnings.
Warnings in /export/jenkins/jobs/Gaia_PR_checker/workspace/checkstyle/gaia/shared/style/confirm.css
Values of 0 shouldn't have units specified. line 313, col 12
Too many font-size declarations (16), abstraction needed. line undefined, col undefined

**Comment by egorlevichev** [comment]
BTW, it's completely not clear which comments were fixed

**Comment by insjinger** [comment]
i have fixed the issue of base64 and some new changes which were pending.

**Pull request merged**
