### PR TITLE
Bug 1210304 - dynamic list of elements has been added to main-screen

### PR DESCRIPTION
**Pull request by MariaKolesina**
Pin apps list with predetermined number of elements changed to dynamic list

### CODE REVIEW

**Comment by MariaKolesina** [comment]
@TatianaMigacheva @egorlevichev @ruvsmirnov @AlekoNN please review

**Comment by ruvsmirnov** [comment]
I can not set label.
Code looks good from my point of view

**Comment by AlekoNN** [comment]
@harman-red-square/harman-reviewers

**Comment by AlekoNN** [comment]
Closed and reopened by mistake. Tatiana, please proceed with the merge.

**Pull request merged**
