### PR TITLE
Bug 1216931 - Add clock on home screen.

### PR DESCRIPTION
**Pull request by ruvsmirnov**

### CODE REVIEW

**Comment by ruvsmirnov** [comment]
@harman-red-square/harman-reviewers

**Comment by ruvsmirnov** [comment]
File apps/verticalhome/js/pin_app_navigation.js has modifications related to restyling code.
Tabs were changed to spaces

**Comment by ruvsmirnov** [comment]
:+1:

**Comment by MariaKolesina** [comment]
Clock in homescreen has not been changing time-format, when time-format was changed in settings (from 24-hours to 12-hours)

**Comment by MariaKolesina** [comment]
Looks good for me

**Pull request merged**
